### ISSUE TITLE
PaymentIntent

### ISSUE THREAD

**Issue by lukadriel7** [cartalyst/stripe#119] opened 2019-01-15 05:33 UTC
Hello, I Just wanted to ask if PaymentIntent was supported and if not, is there any plans to implement it ?

**Comment by brunogaspar** [comment] 2019-01-19 00:32
Hello @lukadriel7 

Yes, this is on my todo list.

Going to close this though as it's a duplicate of #117

**Closed by brunogaspar** 2019-01-19 00:32 UTC
